config/routes.rb
Rails.application.routes.draw do
  # Spree routes
  mount Spree::Core::Engine, at: '/'
  Spree::Core::Engine.add_routes do
    namespace :admin, path: Spree.admin_path do
      resources :badges
      resources :badge_products
    end
  end
  # sidekiq web UI
  require 'sidekiq/web'
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == Rails.application.secrets.sidekiq_username &&
      password == Rails.application.secrets.sidekiq_password
  end
  mount Sidekiq::Web, at: '/sidekiq'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/spree/badge.rb
module Spree
  class Badge < ApplicationRecord
    validates :name, uniqueness: true, presence: true
    has_many :badge_products, class_name: 'Spree::BadgeProduct', dependent: :destroy
    has_many :products, class_name: 'Spree::Product', through: :badge_products
  end
end

app/models/spree/badge_product.rb
module Spree
  class BadgeProduct < ApplicationRecord
    belongs_to :badge, class_name: 'Spree::Badge'
    belongs_to :product, class_name: 'Spree::Product'
  end
end

app/models/spree/product_decorator.rb
module Spree
  module ProductDecorator
    def self.prepended(base)
      base.has_many :badge_products, class_name: 'Spree::BadgeProduct', foreign_key: 'product_id', dependent: :destroy
      base.has_many :badges, class_name: 'Spree::Badge', through: :badge_products
    end
  end
end
::Spree::Product.prepend Spree::ProductDecorator if ::Spree::Product.included_modules.exclude?(Spree::ProductDecorator)

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/badge_products_controller.rb
class BadgeProductsController < ApplicationController
  def create
    @badge_products = BadgeProduct.new(product: params[:product], badge: params[:badge])
  end

  def destroy

  end
end

app/controllers/spree/admin/badges_controller.rb
module Spree
  module Admin
    class BadgesController < Spree::Admin::ResourceController
    end
  end
end

app/controllers/spree/admin/products_controller_decorator.rb
module Spree
  module Admin
    module ProductsControllerDecorator
      def self.prepended(base)
        base.before_action :set_badges, only: %i[edit]
      end

      private

      def set_badges
        @badges = Spree::Badge.all.sort_by(&:name)
      end
    end
  end
end
if ::Spree::Admin::ProductsController.included_modules.exclude?(Spree::Admin::ProductsControllerDecorator)
  ::Spree::Admin::ProductsController.prepend Spree::Admin::ProductsControllerDecorator
end

app/helpers/application_helper.rb
module ApplicationHelper; end

app/helpers/badge_products_helper.rb
module BadgeProductsHelper
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/views/spree/admin/badges/_form.html.erb
<div class="row">
  <div class="col-12 col-lg-6" data-hook="admin_zone_form_fields">
    <div class="card mb-3">
      <div class="card-header">
        <h5 class="card-title mb-0 h6"><%= Spree.t(:general_settings) %></h5>
      </div>

      <div class="card-body">
        <%= badge_form.field_container :name do %>
          <%= badge_form.label :name, Spree.t(:name) %>
          <%= badge_form.text_field :name, class: 'form-control' %>
          <%= badge_form.error_message_on :name %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/spree/admin/badges/edit.html.erb
<% content_for :page_title do %>
  <%= link_to Spree.t(:badges), spree.admin_badges_url %> /
  <%= @badge.name %>
<% end %>
<%= render partial: 'spree/admin/shared/error_messages', locals: { target: @badge } %>
<%= form_for [:admin, @badge] do |badge_form| %>
  <%= render partial: 'form', locals: { badge_form: badge_form } %>
  <%= render partial: 'spree/admin/shared/edit_resource_links' %>
<% end %>

app/views/spree/admin/badges/index.html.erb
<% content_for :page_title do %>
  <%= Spree.t(:badges) %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to Spree.t(:new_badge), new_object_url, class: "btn-success", icon: 'add.svg', id: 'admin_new_zone_link' %>
<% end if can? :create, Spree::Badge %>


<% if @badges.any? %>
  <div class="table-responsive">
    <table class="table" id='listing_badges'>
      <thead>
        <tr>
          <th><%= Spree.t(:name) %></th>
          <th class="d-flex justify-content-end mr-3">Actions</th>
        </tr>
      </thead>
      <tbody>
      <% @badges.each do |badge| %>
        <tr id="<%= spree_dom_id badge %>">
          <td><%= badge.name %></td>

          <td class="actions">
            <span class="d-flex justify-content-end">
              <%= link_to_edit(badge, no_text: true) if can? :edit, badge %>
              <%= link_to_delete(badge, no_text: true) if can? :delete, badge %>
            </span>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
<% else %>
  <div class="text-center no-objects-found m-5">
    <%= Spree.t(:no_resource_found, resource: plural_resource_name(Spree::Badge)) %>,
    <%= link_to(Spree.t(:add_one), new_object_url) if can? :create, Spree::Badge %>!
  </div>
<% end %>

app/views/spree/admin/badges/new.html.erb
<% content_for :page_title do %>
  <%= link_to Spree.t(:badges), spree.admin_badges_url %> /
  <%= Spree.t(:new_badge) %>
<% end %>

<%= render partial: 'spree/admin/shared/error_messages', locals: { target: @badge } %>
<%= form_for [:admin, @badge] do |badge_form| %>
  <%= render partial: 'form', locals: { badge_form: badge_form } %>
  <%= render partial: 'spree/admin/shared/new_resource_links' %>
<% end %>

app/views/spree/admin/products/_form.html.erb
<div data-hook="admin_product_form_fields">
  <div class="row">

    <div class="col-12 col-md-8" data-hook="admin_product_form_left">
      <div data-hook="admin_product_form_name">
        <%= f.field_container :name do %>
          <%= f.label :name, raw(Spree.t(:name) + required_span_tag) %>
          <%= f.text_field :name, class: 'form-control title' %>
          <%= f.error_message_on :name %>
        <% end %>
      </div>

      <div data-hook="admin_product_form_slug">
        <%= f.field_container :slug do %>
          <%= f.label :slug, raw(Spree.t(:slug) + required_span_tag) %>
          <%= f.text_field :slug, class: 'form-control title' %>
          <%= f.error_message_on :slug %>
        <% end %>
      </div>

      <div data-hook="admin_product_form_description">
        <%= f.field_container :description do %>
          <%= f.label :description, Spree.t(:description) %>
          <%= f.text_area :description, { rows: "#{unless @product.has_variants? then '29' else '30' end}", class: "form-control #{"spree-rte" if product_wysiwyg_editor_enabled? }" } %>
          <%= f.error_message_on :description %>
        <% end %>
      </div>
    </div>

    <div class="col-12 col-md-4" data-hook="admin_product_form_right">
      <div data-hook="admin_product_form_price">
        <%= f.field_container :price do %>
          <%= f.label :price, raw(Spree.t(:master_price) + required_span_tag) %>
          <div class="input-group">
            <div class="input-group-prepend">
              <span class="input-group-text"><%= currency_symbol(current_currency) %></span>
            </div>
            <%= f.text_field :price, value: number_to_currency(@product.amount_in(current_currency), unit: ''), class: 'form-control', disabled: (cannot? :update, @product.master.default_price) %>
          </div>
          <%= f.error_message_on :price %>
        <% end %>
      </div>

      <div>
        <%= f.field_container :compare_at_price do %>
          <%= f.label :compare_at_price, Spree.t(:compare_at_price) %>
          <div class="input-group">
            <div class="input-group-prepend">
              <span class="input-group-text"><%= currency_symbol(current_currency) %></span>
            </div>
            <%= f.text_field :compare_at_price, value: number_to_currency(@product.compare_at_amount_in(current_currency), unit: ''), class: 'form-control' %>
          </div>
          <%= f.error_message_on :compare_at_price %>
        <% end %>
      </div>

      <div data-hook="admin_product_form_cost_price" class="alpha two columns">
        <%= f.field_container :cost_price do %>
          <%= f.label :cost_price, Spree.t(:cost_price) %>
          <%= f.text_field :cost_price, value: number_to_currency(@product.cost_price, unit: ''), class: 'form-control' %>
          <%= f.error_message_on :cost_price %>
        <% end %>
      </div>
      <div data-hook="admin_product_form_cost_currency" class="omega two columns">
        <%= f.field_container :cost_currency do %>
          <%= f.label :cost_currency, Spree.t(:cost_currency) %>
          <%= f.select :cost_currency, currency_options(@product.cost_currency), {}, { class: 'select2' } %>
          <%= f.error_message_on :cost_currency %>
        <% end %>
      </div>

      <div data-hook="admin_product_form_available_on">
        <%= f.field_container :available_on do %>
          <%= f.label :available_on, Spree.t(:available_on) %>
          <%= f.error_message_on :available_on %>

          <div class="input-group datePickerFrom"
               data-wrap="true"
               data-alt-format="<%= Spree.t(:fpr_human_friendly_date_format, scope: 'date_picker', default: 'M j, Y') %>"
               data-max-date="<%= @product.discontinue_on %>">

            <%= f.text_field :available_on,
                             value: datepicker_field_value(@product.available_on),
                             placeholder: Spree.t(:select_a_date),
                             class: 'form-control shadow-none ',
                             'data-input':'' %>

            <%= render partial: 'spree/admin/shared/cal_close' %>
          </div>
        <% end %>
      </div>

      <div data-hook="admin_product_form_discontinue_on">
        <%= f.field_container :discontinue_on do %>
          <%= f.label :discontinue_on, Spree.t(:discontinue_on) %>
          <%= f.error_message_on :discontinue_on %>

          <div class="input-group datePickerTo"
               data-wrap="true"
               data-alt-format="<%= Spree.t(:fpr_human_friendly_date_format, scope: 'date_picker', default: 'M j, Y') %>"
               data-min-date="<%= @product.available_on %>">

            <%= f.text_field :discontinue_on,
                             value: datepicker_field_value(@product.discontinue_on),
                             placeholder: Spree.t(:select_a_date),
                             class: 'form-control shadow-none ',
                             'data-input':'' %>

            <%= render partial: 'spree/admin/shared/cal_close' %>
          </div>
        <% end %>
      </div>

      <div data-hook="admin_product_form_promotionable">
        <%= f.field_container :promotionable do %>
          <%= f.check_box :promotionable %>
          <%= f.label :promotionable, Spree.t(:promotionable) %>
          <%= f.error_message_on :promotionable %>
        <% end %>
      </div>

      <div>
        <%= f.field_container :badges do %>
          <%= f.label :badges %>
          <%= collection_select(:product, :badge_ids, @badges, :id, :name, {}, { multiple: true, class: 'select2' }) %>
        <% end %>
      </div>


      <div data-hook="admin_product_form_sku">
        <%= f.field_container :master_sku do %>
          <%= f.label :master_sku, Spree.t(:master_sku) %>
          <%= f.text_field :sku, size: 16, class: 'form-control' %>
        <% end %>
      </div>

      <% if @product.has_variants? %>
        <div data-hook="admin_product_form_multiple_variants" class="card bg-light mb-3">
          <div class="card-body">
            <h5 class="card-title"><%= f.label :skus, Spree.t(:sku).pluralize %></h5>
            <h6 class="card-subtitle mb-2 text-muted"><%= Spree.t(:info_product_has_multiple_skus, count: @product.variants.size) %> </h6>
            <ul class="list-unstyled">
              <% @product.variants.first(5).each do |variant| %>
                <li><%= variant.sku %></li>
              <% end %>
            </ul>
            <% if @product.variants.size > 5 %>
              <em>
                <%= Spree.t(:info_number_of_skus_not_shown, count: @product.variants.size - 5) %>
              </em>
            <% end %>
            <div class="info-actions">
              <% if can?(:admin, Spree::Variant) %>
                <%= link_to_with_icon 'adjust.svg', Spree.t(:manage_variants), spree.admin_product_variants_url(@product), class: "btn btn-outline-secondary" %>
              <% end %>
            </div>
          </div>
        </div>
      <% else %>
        <div id="shipping_specs" class="row">
          <div class="col-12 col-md-6">
            <div id="shipping_specs_weight_field" data-hook="admin_product_form_weight" class="form-group">
              <%= f.label :weight, Spree.t(:weight) %>
              <%= f.text_field :weight, value: number_with_precision(@product.weight, precision: 2), size: 4, class: 'form-control' %>
            </div>
          </div>

          <div class="col-12 col-md-6">
            <div id="shipping_specs_height_field" data-hook="admin_product_form_height" class="form-group">
              <%= f.label :height, Spree.t(:height) %>
              <%= f.text_field :height, value: number_with_precision(@product.height, precision: 2), size: 4, class: 'form-control' %>
            </div>
          </div>

          <div class="col-12 col-md-6">
            <div id="shipping_specs_width_field" data-hook="admin_product_form_width" class="form-group">
              <%= f.label :width, Spree.t(:width) %>
              <%= f.text_field :width, value: number_with_precision(@product.width, precision: 2), size: 4, class: 'form-control' %>
            </div>
          </div>

          <div class="col-12 col-md-6">
            <div id="shipping_specs_depth_field" data-hook="admin_product_form_depth" class="form-group">
              <%= f.label :depth, Spree.t(:depth) %>
              <%= f.text_field :depth, value: number_with_precision(@product.depth, precision: 2), size: 4, class: 'form-control' %>
            </div>
          </div>
        </div>
      <% end %>

      <div data-hook="admin_product_form_shipping_categories">
        <%= f.field_container :shipping_category do %>
          <%= f.label :shipping_category_id, Spree.t(:shipping_category) %>
          <%= f.collection_select(:shipping_category_id, @shipping_categories, :id, :name, { include_blank: Spree.t('match_choices.none') }, { class: 'select2' }) %>
          <%= f.error_message_on :shipping_category %>
        <% end %>
      </div>

      <div data-hook="admin_product_form_tax_category">
        <%= f.field_container :tax_category do %>
          <%= f.label :tax_category_id, Spree.t(:tax_category) %>
          <%= f.collection_select(:tax_category_id, @tax_categories, :id, :name, { include_blank: Spree.t('match_choices.none') }, { class: 'select2' }) %>
          <%= f.error_message_on :tax_category %>
        <% end %>
      </div>
    </div>

  </div>

  <div data-hook="admin_product_form_taxons">
    <%= f.field_container :taxons do %>
      <%= f.label :taxon_ids, Spree.t(:taxons) %>

      <% if can? :modify, Spree::Classification %>
        <%= f.select :taxon_ids, options_from_collection_for_select(@product.taxons, :id, :pretty_name, @product.taxon_ids),
                     { include_hidden: true },
                     multiple: true,
                     data: { autocomplete_url_value: 'taxons_api_v2',
                             autocomplete_return_attr_value: 'pretty_name',
                             autocomplete_multiple_value: true } %>
      <% elsif @product.taxons.any? %>
        <ul class="text_list">
          <% @product.taxons.each do |taxon| %>
            <li><%= taxon.name %></li>
          <% end %>
        </ul>
      <% else %>
        <div class="alert alert-info"><%= Spree.t(:no_resource_found, resource: :taxons) %></div>
      <% end %>

    <% end %>
  </div>

  <div data-hook="admin_product_form_option_types">
    <%= f.field_container :option_types do %>
      <%= f.label :option_type_ids, Spree.t(:option_types) %>

      <% if can? :modify, Spree::ProductOptionType %>
        <%= f.select :option_type_ids, options_from_collection_for_select(@product.option_types, :id, :name, @product.option_type_ids),
                     { include_hidden: true },
                     multiple: true,
                     data: { autocomplete_url_value: 'option_types_api_v2',
                             autocomplete_return_attr_value: 'name',
                             autocomplete_multiple_value: true } %>
      <% elsif @product.option_types.any? %>
        <ul class="text_list">
          <% @product.option_types.each do |type| %>
            <li><%= type.presentation %> (<%= type.name %>)</li>
          <% end %>
        </ul>
      <% else %>
        <div class="alert alert-info"><%= Spree.t(:no_resource_found, resource: :option_types) %></div>
      <% end %>

    <% end %>
  </div>

  <% if @stores.count > 1 %>
    <div data-hook="admin_product_form_stores">
      <%= f.field_container :stores do %>
        <%= f.label :product_stores, Spree.t(:stores) %>
        <%= collection_select(:product, :store_ids, @stores, :id, :unique_name, {}, { multiple: true, class: 'select2' }) %>
      <% end %>
    </div>
  <% end %>

  <div data-hook="admin_product_form_meta">
    <div data-hook="admin_product_form_meta_title">
      <%= f.field_container :meta_title do %>
        <%= f.label :meta_title, Spree.t(:meta_title) %>
        <%= f.text_field :meta_title, class: 'form-control' %>
      <% end %>
    </div>

    <div data-hook="admin_product_form_meta_keywords">
      <%= f.field_container :meta_keywords do %>
        <%= f.label :meta_keywords, Spree.t(:meta_keywords) %>
        <%= f.text_field :meta_keywords, class: 'form-control' %>
      <% end %>
    </div>

    <div data-hook="admin_product_form_meta_description">
      <%= f.field_container :meta_description do %>
        <%= f.label :meta_description, Spree.t(:meta_description) %>
        <%= f.text_area :meta_description, class: 'form-control' %>
      <% end %>
    </div>

    <div data-hook="admin_product_form_additional_fields"></div>

  </div>
</div>

app/views/spree/admin/shared/sub_menu/_configuration.html.erb
<ul data-hook="admin_configurations_sidebar_menu" class="collapse nav nav-pills nav-stacked" id="sidebar-configuration">
  <%= configurations_sidebar_menu_item(Spree.t(:general_settings), spree.edit_admin_general_settings_path) if can? :manage, Spree::Config %>
  <%= configurations_sidebar_menu_item(Spree.t(:stores), spree.admin_stores_path) if can? :manage, Spree::Store %>
  <%= configurations_sidebar_menu_item(Spree.t(:tax_categories), spree.admin_tax_categories_path) if can? :manage, Spree::TaxCategory %>
  <%= configurations_sidebar_menu_item(Spree.t(:tax_rates), spree.admin_tax_rates_path) if can? :manage, Spree::TaxRate %>
  <%= configurations_sidebar_menu_item(Spree.t(:zones), spree.admin_zones_path) if can? :manage, Spree::Zone %>
  <%= configurations_sidebar_menu_item(Spree.t(:countries), spree.admin_countries_path) if can? :manage, Spree::Country %>

  <% if country = current_store.default_country %>
    <%= configurations_sidebar_menu_item(Spree.t(:states), spree.admin_country_states_path(country)) if can? :manage, Spree::Country %>
  <% end %>

  <%= configurations_sidebar_menu_item(Spree.t(:payment_methods), spree.admin_payment_methods_path) if can? :manage, Spree::PaymentMethod %>
  <%= configurations_sidebar_menu_item(Spree.t(:shipping_methods), spree.admin_shipping_methods_path) if can? :manage, Spree::ShippingMethod %>
  <%= configurations_sidebar_menu_item(Spree.t(:shipping_categories), spree.admin_shipping_categories_path) if can? :manage, Spree::ShippingCategory %>
  <%= configurations_sidebar_menu_item(Spree.t(:store_credit_categories), spree.admin_store_credit_categories_path) if can? :manage, Spree::StoreCreditCategory %>
  <%= configurations_sidebar_menu_item(Spree.t(:refund_reasons), spree.admin_refund_reasons_path) if can? :manage, Spree::RefundReason %>
  <%= configurations_sidebar_menu_item(Spree.t(:reimbursement_types), spree.admin_reimbursement_types_path) if can? :manage, Spree::ReimbursementType %>
  <%= configurations_sidebar_menu_item(Spree.t(:return_authorization_reasons), spree.admin_return_authorization_reasons_path) if can? :manage, Spree::ReturnAuthorizationReason %>
  <%= configurations_sidebar_menu_item(Spree.t(:roles), spree.admin_roles_path) if can? :manage, Spree::Role %>
  <%= configurations_sidebar_menu_item(Spree.t(:badges), spree.admin_badges_path) if can? :manage, Spree::Badge %>
</ul>